### PR TITLE
fix issue #3 / add example

### PR DESCRIPTION
**Pull request by RenatFakhrutdinov**
Solution for issue #3 
example of using this lib

### CODE REVIEW

**Comment by rchowell** [comment]
Thank you!

**Comment by RenatFakhrutdinov** [comment]
@RCHowell great but could you publish updates here
https://pub.dev/packages/flutter_plot

Usually users import libraries from pub.dev so I suppose we need publish fixed version of this lib

**Comment by rchowell** [comment]
I’m working on that now. I made this years ago with an email that no longer exists. I need to add my latest Google account as a publisher, but I can’t set new permissions since I have no access to the previous account. 

I’ve reached out to pub.dev support

**Comment by rchowell** [comment]
Support was very helpful. I was able to gain ownership with my new email and v0.0.3 is available. Thank you for the pr!!

**Pull request merged**
